#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-only
# Copyright (C) 2026 James Morris <jamorris@linux.microsoft.com>

set -euo pipefail
export LC_ALL=C

usage() {
    cat >&2 <<'EOF'
Usage:
  update-index.sh [--check]

Regenerates SECURITY-REVIEWS.md from reviews/SR-*/scope.md and
syntheses/SRS-*/scope.md. With --check, exits 1 when the file would change.
EOF
}

die() {
    printf 'update-index: ERROR: %s\n' "$*" >&2
    exit 1
}

repository_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P) ||
    die "cannot resolve repository root"
cd -- "$repository_root"

check=false
if (($# == 1)) && [[ $1 == --check ]]; then
    check=true
elif (($# != 0)); then
    usage
    exit 2
fi

temporary=$(mktemp "${TMPDIR:-/tmp}/security-review-index.XXXXXX") ||
    die "cannot create temporary index"
cleanup() {
    rm -f -- "$temporary"
}
trap cleanup EXIT

metadata() {
    local label=$1 file=$2
    sed -n 's/^'"$label"': `\([^`]*\)`$/\1/p' "$file" | head -n 1
}

plain_metadata() {
    local label=$1 file=$2
    sed -n "s/^$label: //p" "$file" | head -n 1
}

# Prints the first data row of the table that follows the given H2 heading.
first_table_row() {
    local heading=$1 file=$2
    awk -v heading="$heading" '
        $0 == heading { active=1; next }
        active && /^## / { exit }
        active && /^\|/ {
            rows++
            if (rows == 3) { print; exit }
        }
    ' "$file"
}

cell() {
    local row=$1 index=$2 value
    value=$(printf '%s\n' "$row" | awk -F '|' -v column="$index" '{
        value=$(column + 1)
        gsub(/^[ \t]+|[ \t]+$/, "", value)
        gsub(/`/, "", value)
        print value
    }')
    printf '%s' "$value"
}

{
    printf '<!-- SPDX-License-Identifier: GPL-3.0-only -->\n'
    printf '<!-- Copyright (C) 2026 James Morris <jamorris@linux.microsoft.com> -->\n'
    printf '<!-- Generated by scripts/update-index.sh. Do not edit by hand. -->\n\n'
    printf '# Security reviews\n\n'
    printf 'Generated index of review packages (`reviews/SR-*/`) and synthesis\n'
    printf 'packages (`syntheses/SRS-*/`). A listed package is a private record of an\n'
    printf 'independent review; it is not approval, acceptance, or sign-off.\n\n'

    printf '## Reviews\n\n'
    shopt -s nullglob
    packages=(reviews/SR-*/)
    shopt -u nullglob
    if ((${#packages[@]} == 0)); then
        printf 'No review packages recorded.\n'
    else
        printf '| Package ID | Title | Created | Status | Phase | Execution | Distribution | Target | Latest iteration |\n'
        printf '| --- | --- | --- | --- | --- | --- | --- | --- | --- |\n'
        for package in "${packages[@]}"; do
            package=${package%/}
            scope=$package/scope.md
            [[ -f $scope ]] || die "package is missing scope.md: $package"
            id=$(metadata 'Package ID' "$scope")
            title=$(plain_metadata 'Title' "$scope")
            created=$(plain_metadata 'Created' "$scope")
            status=$(metadata 'Status' "$scope")
            phase=$(metadata 'Phase' "$scope")
            execution=$(metadata 'Execution' "$scope")
            distribution=$(metadata 'Distribution' "$scope")
            iteration=$(metadata 'Latest review iteration' "$scope")
            row=$(first_table_row '## Target snapshot' "$scope")
            target=$(cell "$row" 1)
            [[ -n $id && -n $title && -n $created && -n $status && -n $phase &&
                -n $execution && -n $distribution && -n $iteration ]] ||
                die "scope metadata is incomplete: $scope"
            [[ $id == "${package#reviews/}" ]] ||
                die "scope Package ID does not match the directory: $scope"
            [[ -n $target ]] || target='Not recorded'
            printf '| [%s](%s/SECURITY-REVIEW.md) | %s | %s | `%s` | `%s` | `%s` | `%s` | %s | `%s` |\n' \
                "$id" "$package" "$title" "$created" "$status" "$phase" \
                "$execution" "$distribution" "$target" "$iteration"
        done
    fi

    printf '\n## Syntheses\n\n'
    shopt -s nullglob
    packages=(syntheses/SRS-*/)
    shopt -u nullglob
    if ((${#packages[@]} == 0)); then
        printf 'No synthesis packages recorded.\n'
    else
        printf '| Package ID | Title | Created | Status | Distribution | Inputs | Latest iteration |\n'
        printf '| --- | --- | --- | --- | --- | --- | --- |\n'
        for package in "${packages[@]}"; do
            package=${package%/}
            scope=$package/scope.md
            [[ -f $scope ]] || die "package is missing scope.md: $package"
            id=$(metadata 'Package ID' "$scope")
            title=$(plain_metadata 'Title' "$scope")
            created=$(plain_metadata 'Created' "$scope")
            status=$(metadata 'Status' "$scope")
            distribution=$(metadata 'Distribution' "$scope")
            iteration=$(metadata 'Latest synthesis iteration' "$scope")
            [[ -n $id && -n $title && -n $created && -n $status &&
                -n $distribution && -n $iteration ]] ||
                die "scope metadata is incomplete: $scope"
            [[ $id == "${package#syntheses/}" ]] ||
                die "scope Package ID does not match the directory: $scope"
            inputs=$(awk -F '|' '
                $0 == "## Input packages" { active=1; next }
                active && /^## / { exit }
                active && /^\|/ {
                    rows++
                    if (rows < 3) next
                    value=$2
                    gsub(/^[ \t]+|[ \t]+$/, "", value)
                    gsub(/`/, "", value)
                    if (value ~ /^SR-[0-9]{8}-[0-9]{3}-/) {
                        list = (list == "" ? value : list ", " value)
                    }
                }
                END { print (list == "" ? "None" : list) }
            ' "$scope")
            printf '| [%s](%s/synthesis.md) | %s | %s | `%s` | `%s` | %s | `%s` |\n' \
                "$id" "$package" "$title" "$created" "$status" \
                "$distribution" "$inputs" "$iteration"
        done
    fi
} >"$temporary"

if $check; then
    [[ -f SECURITY-REVIEWS.md ]] || die "SECURITY-REVIEWS.md is missing"
    cmp -s -- "$temporary" SECURITY-REVIEWS.md ||
        die "SECURITY-REVIEWS.md is stale; run scripts/update-index.sh"
else
    mv -- "$temporary" SECURITY-REVIEWS.md
    chmod 644 SECURITY-REVIEWS.md
    trap - EXIT
    printf 'updated SECURITY-REVIEWS.md\n'
fi
